blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://t.me/ksunext/578
    about: "We do not accept external Feature Requests anymore, check the link for more details."
